export const posts = [
    {
        slug: "history",
        title: "История",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu dignissim neque, vel consequat erat. Pellentesque vitae massa interdum, maximus metus et, malesuada neque. Etiam eget sodales libero. Ut tristique, felis ut dignissim semper, mi dui gravida sem, in vehicula diam diam a tellus. Nam ultrices, ipsum nec posuere facilisis, justo risus rutrum ante, non placerat nisi eros quis lectus. Maecenas vel pharetra ligula. Nullam quis interdum lorem.Mauris lacus libero, molestie eget lacus id, placerat auctor odio. Nullam eros leo, tristique ut hendrerit et, condimentum sed massa. Quisque condimentum velit placerat tincidunt gravida. Pellentesque volutpat eleifend maximus. In consequat lacus vitae rutrum facilisis. Nam facilisis ligula sed justo congue, egestas consequat nibh finibus. Suspendisse ut fringilla dolor, ut ornare justo. Praesent tortor ante, dignissim eu dignissim at, auctor sit amet purus. Sed interdum nulla arcu, quis egestas nisi mollis ut. Mauris et vulputate libero. Nulla dictum leo et tellus ultrices hendrerit. Sed nec dignissim quam, id scelerisque nibh. Nulla non tempor quam. Sed viverra, justo sed tempus feugiat, elit libero rutrum nunc, sodales pharetra augue ex vitae mauris.",
    },
    {
        slug: "landmarks",
        title: "Достопримечательности",
        text: "Mauris quis ipsum viverra, sagittis quam vitae, pharetra nulla. Etiam a rutrum quam, et sodales velit. Praesent porttitor eget odio vitae pellentesque. Praesent convallis, orci vitae commodo euismod, ipsum augue rutrum nulla, eu fringilla elit nisl a mauris. Suspendisse eu arcu a ligula semper fringilla vel id purus. Cras ultricies mollis lectus, id consectetur diam tempor in. Sed accumsan aliquet lacus id tincidunt. Morbi a purus turpis. Maecenas dictum vitae tellus quis placerat. Quisque pretium dictum est non dapibus. Etiam at augue congue, imperdiet ligula vitae, porttitor arcu. In vitae finibus enim. Nullam eget molestie ipsum. Vestibulum vitae est odio. Donec consequat augue vitae dignissim tincidunt. Nulla purus neque, tempor congue blandit mollis, consectetur eget turpis. Vivamus ornare egestas velit, at tincidunt quam efficitur ut. Fusce blandit scelerisque tellus, vitae elementum magna accumsan id. Sed enim nisl, congue sed diam vel, finibus interdum metus. In efficitur semper tellus in volutpat. Donec auctor mauris in nulla tempor dictum. In rhoncus justo vitae neque sagittis posuere. Pellentesque porttitor convallis nibh sit amet tincidunt.",
    },
    {
        slug: "education",
        title: "Учебные заведения",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu dignissim neque, vel consequat erat. Pellentesque vitae massa interdum, maximus metus et, malesuada neque. Etiam eget sodales libero. Ut tristique, felis ut dignissim semper, mi dui gravida sem, in vehicula diam diam a tellus. Nam ultrices, ipsum nec posuere facilisis, justo risus rutrum ante, non placerat nisi eros quis lectus. Maecenas vel pharetra ligula. Nullam quis interdum lorem.Mauris lacus libero, molestie eget lacus id, placerat auctor odio. Nullam eros leo, tristique ut hendrerit et, condimentum sed massa. Quisque condimentum velit placerat tincidunt gravida. Pellentesque volutpat eleifend maximus. In consequat lacus vitae rutrum facilisis. Nam facilisis ligula sed justo congue, egestas consequat nibh finibus. Suspendisse ut fringilla dolor, ut ornare justo. Praesent tortor ante, dignissim eu dignissim at, auctor sit amet purus. Sed interdum nulla arcu, quis egestas nisi mollis ut. Mauris et vulputate libero. Nulla dictum leo et tellus ultrices hendrerit. Sed nec dignissim quam, id scelerisque nibh. Nulla non tempor quam. Sed viverra, justo sed tempus feugiat, elit libero rutrum nunc, sodales pharetra augue ex vitae mauris.",
    },
    {
        slug: "recreation",
        title: "Отдых",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu dignissim neque, vel consequat erat. Pellentesque vitae massa interdum, maximus metus et, malesuada neque. Etiam eget sodales libero. Ut tristique, felis ut dignissim semper, mi dui gravida sem, in vehicula diam diam a tellus. Nam ultrices, ipsum nec posuere facilisis, justo risus rutrum ante, non placerat nisi eros quis lectus. Maecenas vel pharetra ligula. Nullam quis interdum lorem.Mauris lacus libero, molestie eget lacus id, placerat auctor odio. Nullam eros leo, tristique ut hendrerit et, condimentum sed massa. Quisque condimentum velit placerat tincidunt gravida. Pellentesque volutpat eleifend maximus. In consequat lacus vitae rutrum facilisis. Nam facilisis ligula sed justo congue, egestas consequat nibh finibus. Suspendisse ut fringilla dolor, ut ornare justo. Praesent tortor ante, dignissim eu dignissim at, auctor sit amet purus. Sed interdum nulla arcu, quis egestas nisi mollis ut. Mauris et vulputate libero. Nulla dictum leo et tellus ultrices hendrerit. Sed nec dignissim quam, id scelerisque nibh. Nulla non tempor quam. Sed viverra, justo sed tempus feugiat, elit libero rutrum nunc, sodales pharetra augue ex vitae mauris.",
    },
];
